/**
 * QZ Tray public certificate — used to verify the identity of this application.
 * The matching private key is stored in QZ_PRIVATE_KEY env var (server-side only).
 * This certificate is NOT secret — it's the public half of the keypair.
 */
export const QZ_CERT = `-----BEGIN CERTIFICATE-----
MIIDWTCCAkGgAwIBAgIUOC7smuwG6dfr8/ANe0sUuwR47YkwDQYJKoZIhvcNAQEL
BQAwPDEWMBQGA1UEAwwNTE5EUllPUyBQcmludDEVMBMGA1UECgwMVGhlIExORFJZ
IENvMQswCQYDVQQGEwJDQTAeFw0yNjA2MDIwOTI1MjNaFw0zNjA1MzAwOTI1MjNa
MDwxFjAUBgNVBAMMDUxORFJZT1MgUHJpbnQxFTATBgNVBAoMDFRoZSBMTkRSWSBD
bzELMAkGA1UEBhMCQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDJ
nBZAXR5Q74MWft90hNJSUAJQldytwEJ6oIRl+X3RnOeJkTWjkBjtp2YZMvs7aILD
ozEjv/jiuynzXqj04YIF3TN8PPddalD/OQ68oOid2HSuKHHNB062XcU9wDf9Womh
evEF4iFes+/H4on1cky3Yyal2CsZkoPpnllArGtNp7+8+Ik2JmCRgWADNDo+xxfa
m71EG6XL7CR+v05t/TPjhF8Wf8D6e3IwOl+untqQavFNgQL+O6tIZf6oluExCI00
h2C0G/dj7Hjg3p/Uj3dUEmaP9mRhra9HclyuGB+1eGW5moM+ZffDKSGYwBFPF2j7
ACLR9RcKyRYWhYka9eFZAgMBAAGjUzBRMB0GA1UdDgQWBBR9imCbH+yW6S/0Y+dA
CyxWk90V6zAfBgNVHSMEGDAWgBR9imCbH+yW6S/0Y+dACyxWk90V6zAPBgNVHRMB
Af8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAPWoqImJH1bAxio6zEIt5LWCBQ
JMqv+bUiGCx98gr7/e8Vfkg6GHaqkOLxtP0gTCkhcu2Hyn7RakhNfjAIxupXg0xB
MrLb+teFqJ3cfAJSN4HvnFKtdWmdJjgzcG3bG6GBT5EeiaDWAa5+J2fh+U8tiC01
4bwiBfxlM+MomfYXQ+6CknLu6FE44BFdB7eFXch8xZjBFB4vwA8Uj7f/8GdCw1j1
+W+QB+n5vHuM9uXL6ZQD8efusnvyFsUQcoERjKS3y3f4XOwhfEKu8JdOkAOsCe2R
wE/kg2lmpSku4Ip3xX94LV6WSHWU+MonlBcW6wR4TrhvtsM6DWdUbMGC4pkx
-----END CERTIFICATE-----`
